name: teambey_org
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  
  assets:
    - assets/images/
  
  fonts:
    - family: Rubik-Italic
      fonts:
        - asset: assets/fonts/Rubik-Italic.ttf
        
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat.ttf
  #       # - asset: fonts/TrajanPro_Bold.ttf
  #       # - asset: fonts/TrajanPro_Bold.ttf
  # #         weight: 700
  #
